"""Initial migration

Revision ID: 6e89d88d979c
Revises: 
Create Date: 2024-02-27 21:49:07.302465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e89d88d979c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.Enum('start', 'message', 'condition', 'end', name='nodetypes'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condition_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('opened', 'pending', 'sent', name='messagestatus'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_node_id', sa.Integer(), nullable=True),
    sa.Column('end_node_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['end_node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['start_node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('opened', 'pending', 'sent', name='messagestatus'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_node')
    op.drop_table('edge')
    op.drop_table('condition_node')
    op.drop_table('node')
    # ### end Alembic commands ###
