"""Initial migration

Revision ID: a3d27a080132
Revises: 
Create Date: 2024-02-28 15:58:49.503977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d27a080132'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.Enum('start', 'end', 'message', 'condition', name='nodetypes'), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('open', 'pending', 'sent', name='messagestatus'), nullable=True),
    sa.Column('condition', sa.Enum('open', 'pending', 'sent', name='messagestatus'), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('start_node_id', sa.Integer(), nullable=True),
    sa.Column('end_node_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['end_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['start_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edges')
    op.drop_table('nodes')
    op.drop_table('workflows')
    # ### end Alembic commands ###
